#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.cterm"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.cterm" "${2}"
        fi

        # create cterm group if it doesn't exist
        if ! getent group cterm >/dev/null 2>&1; then
            groupadd --system cterm
        fi

        # restart service if running
        term="omv_cterm.service"
        if systemctl is-active --quiet "${term}"; then
            # remove python cache
            rm -rfv /opt/omv_cterm/__pycache__
            # restart service
            systemctl restart "${term}"
        fi

        SECRET_FILE="/etc/omv_cterm.secret"
        if [ ! -f "$SECRET_FILE" ]; then
            head -c 64 /dev/urandom | base64 > "$SECRET_FILE"
            chmod 600 "$SECRET_FILE"
            echo "Generated new secret in $SECRET_FILE"
        else
            echo "Secret file already exists"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
